### ISSUE TITLE
Add scrollbox to Ant editor

### ISSUE THREAD

**Issue by anthonyoffire** [cs481-ekh/s23-scuttlers#231]
As developers, we need scrollboxes for items in the Ant editor so that if items are added to the game at a later date, there is room for them to be automatically displayed.

Acceptance Criteria:
- [x] Given the open Ant editor, when looking at the items, ai's, etc, they should be contained in a scrollbox.

**Comment by Jackcunningolf** [comment]
All of the panes in the ant editor are now scrollable when needed. Also, a lot of logic for displaying buttons is now out of the render method which Dr. Henderson suggested so I'm glad thats working. The only iffy part of this is the font. Because I needed to display buttons in a scrollpane, I also had to display the text in the scrollpane as well. This forced me to use the skin font instead of the game font due to the parameters of the scrollpane. 

{t:300}
